---
- name: Stop EC2 instance
  hosts: 35.177.173.243
  gather_facts: False
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.aws/infra-keypair1.pem

  tasks:
    - name: Stop EC2 instance
      shell: aws ec2 stop-instances --instance-ids i-0985a302cfe7aeebe --region eu-west-2 --output text
      register: stop_output
      args:
        executable: /bin/bash
