---
- name: shutdown ser
  hosts: 35.176.180.40
  gather_facts: False
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/.aws/infra-keypair1.pem

  tasks:
    - name: shutdown s
      become: yes
      become_user: root
      shell: sudo shutdown now
