---
- name: create directory on EC2 Red Hat servers
  hosts: ec2_redhat_servers
  gather_facts: False
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/.aws/infra-keypair1.pem

  tasks:
    - name: create directory
      become: yes
      become_user: root
      file:
        path: /home/ec2-user/my_directory
        state: directory
        mode: "0755"
